CNXC 167
darwinai/pl-pdfgeneration pull request #5
Opened 2021-02-16 15:59 UTC by colinywu

Adjusted python script to dynamically read results from the .json file (based on chosen classification model) and write the data accordingly to the PDF

2021-03-01 18:30 UTC, boris-nguyen requested changes
Great job @colinywu 

I left some comments related to making your changes follow the PEP8. Please, make those changes and I will approve the PR.

2021-03-01 18:30 UTC, boris-nguyen commented on pdfgeneration/pdfgeneration.py
> +            predictionAnalysis = ""
Variable names should be lowercase, with words separated by underscores as necessary to improve readability.

```suggestion
            prediction_analysis = ""
```

You can find guidelines and best practices of coding in Python in the
[PEP 8 documentations](https://www.python.org/dev/peps/pep-0008/).

2021-03-01 18:30 UTC, boris-nguyen commented on pdfgeneration/pdfgeneration.py
> +                predictionAnalysis += "<h3>{title}: <span>{prediction}</span></h3>".format(title = columnName, prediction = classification_data.get(columnName, None))
I believe the python installed in `fnndsc/ubuntu-python3:18.04` is Python >=3.6.

I would highly suggest using f-strings instead of str.format(). When using f-strings. Also, try to avoid making code lines longer than 120 characters. Split the lines where necessary.

2021-03-01 18:30 UTC, boris-nguyen commented on pdfgeneration/pdfgeneration.py
> +                predictionAnalysis += "<h3>{title}: <span>{prediction}</span></h3>".format(title = columnName, prediction = classification_data.get(columnName, None))
```suggestion
                predictionAnalysis += "<h3>{title}: <span>{prediction}</span></h3>".format(title=columnName, prediction=classification_data.get(columnName, None))
```

["Don't use spaces around the = sign when used to indicate a keyword argument, or when used to indicate a default value for an unannotated function parameter"](https://www.python.org/dev/peps/pep-0008/#other-recommendations)

2021-03-01 18:30 UTC, boris-nguyen commented on pdfgeneration/pdfgeneration.py
> +                predictionAnalysis += "<h3>{title}: <span>{prediction}</span></h3>".format(title = columnName, prediction = classification_data.get(columnName, None))
Inconsistent indentation
`PEP 8: E111 indentation is not a multiple of four`

2021-03-01 22:44 UTC, colinywu commented on pdfgeneration/pdfgeneration.py
> +                predictionAnalysis += "<h3>{title}: <span>{prediction}</span></h3>".format(title = columnName, prediction = classification_data.get(columnName, None))
Sorry, can't tell what specific formatting here. Is line 183 incorrectly formatted?

2021-03-02 17:09 UTC, boris-nguyen commented on pdfgeneration/pdfgeneration.py
> +                predictionAnalysis += "<h3>{title}: <span>{prediction}</span></h3>".format(title = columnName, prediction = classification_data.get(columnName, None))
Line 180 and 181 are using 2 spaces instead of 4.

2021-03-02 22:08 UTC, boris-nguyen commented on pdfgeneration/pdfgeneration.py
> +                    prediction_analysis += f"<h3>{columnName}: <span>{prediction}</span></h3>"
Variable names should be lowercase, with words separated by underscores as necessary to improve readability.

You can find guidelines and best practices of coding in Python in the
[PEP 8 documentations](https://www.python.org/dev/peps/pep-0008/).

2021-03-02 22:09 UTC, boris-nguyen commented on pdfgeneration/pdfgeneration.py
> +                prediction=classification_data.get(columnName, 'N/A')
```suggestion
                prediction = classification_data.get(columnName, 'N/A')
```

2021-03-02 22:11 UTC, boris-nguyen approved these changes
Great job @colinywu!

2021-03-10 13:25 UTC, IvanToronto approved these changes

2021-03-10 13:25 UTC, merged